knife4j:
  enable: true
  setting:
    language: zh_cn
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: recommend
    url: jdbc:mysql://demo.ynu.icu:3306/food_recommend
    username: recommend
springdoc:
  api-docs:
    path: /v3/api-docs
  group-configs:
  - group: default
    packages-to-scan: com.example.recommend.railway
    paths-to-match: /**
  swagger-ui:
    operations-sorter: alpha
    path: /swagger-ui.html
    tags-sorter: alpha
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl